---
title: "Tidy Data"
output: github_document
---

```{r setup}
library(tidyverse)
```

## pivot_longer

load the PULSE data

```{r}
pulse_df = 
  haven :: read_sas("./data/public_pulse_Data.sas7bdat") %>% 
  janitor :: clean_names()
pulse_df
```

wide format to long format...

```{r}
pulse_data_tidy =
  pulse_df %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )
pulse_data_tidy
```
combining and extending all into one
recode lets you change observations

```{r}
pulse_df = 
  haven :: read_sas("./data/public_pulse_Data.sas7bdat") %>% 
  janitor :: clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>% 
  relocate(id, visit) %>% 
  mutate (visit = recode(visit, "bl" = "00m"))
pulse_df
```

## pivot wider now
```{r}
analysis_result =
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4,8,3.5,4)
  )
analysis_result %>% 
  pivot_wider(
    names_from = "time", 
    values_from = "mean"
  )
```

## binding rows

binding rows using lord of the rings data

first step: import each data

```{r}
fellowship_ring =
  readxl :: read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring")

two_towers =
  readxl :: read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "two_towers")

return_king =
  readxl :: read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king")
```

bind all of the rows together

```{r}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor :: clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(
    female:male,
    names_to="gender",
    values_to="words"
  )
lotr_tidy
```

## joining datasets

import the FAS datasets

```{r}
pups_df = 
  read_csv("./data/FAS_pups.csv") %>% 
  janitor :: clean_names() %>% 
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))

litters_df = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor :: clean_names() %>% 
  relocate(litter_number) %>% 
  separate(group, into = c("dose", "day_of_tx"), sep = 3)
litters_df
```

next up, time to join them

```{r}
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") %>% 
  arrange(litter_number) %>% 
  relocate(litter_number, dose, day_of_tx)
fas_df 
```




